
# Name of the pack (required)
name: beginner-web-app-pack

# Description of the pack (required)
description: |+
  Thtemplate pack gives the basics of web app observability!

# Support level: New Relic | Verified | Community (required)
level: Community

# Design
icon: icon.jpeg
logo: logo.png
website: https://www.newrelic.com

# Authors of the pack (required)
authors:
    - New Relic
    - Darren Doyle
    - Alex York

# Instrumentation (optional)
# This allows you to define which instrumentation is needed for your pack
# Any file in the instrumentation folder will automatically be picked up

#TODO: Add New Relic browser agent

instrumentation:
  # Example for New Relic On Host Integrations
  # Possible values: apache, cassandra, couchbase, collectd, elasticsearch, amazon-ecs, f5, go-insights-monitoring, haproxy, hashicorp-consul, jmx, kafka, kubernetes, memcached, mongodb, mssql, mysql, nagios, nfs, nginx, oracledb, postgresql, rabbitmq, redis, snmp, unix-monitoring, varnish-cache, vmware-vsphere, vmware-tanzu, zookeeper
  - type: newrelic-infra-ohi
    name: nginx
  # Example for New Relic APM Agent
  # Possible values: c, golang, java, dotnet, dotnet-core, nodejs, php, python, ruby
  - type: newrelic-apm
    name: java
  # Example for New Relic Cloud integration
  # Possible values can be found on our docs:
  # - AWS (aws): https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/
  # - Azure (azure): https://docs.newrelic.com/docs/integrations/microsoft-azure-integrations/azure-integrations-list/
  # - Google Cloud (gcp): https://docs.newrelic.com/docs/integrations/google-cloud-platform-integrations/gcp-integrations-list/
  # The value of name should be the cloud provider + the name of the service in lowercase. For example: `aws-rds`, `azure-cosmosdb`, `gcp-bigquery`.
  # - type: newrelic-cloud-integration
  #   name: aws-s3
  # # Example for Prometheus Exporter
  # # The url should point to a repository containing the prometheus exporter
  # - type: prometheus
  #   url: https://github.com/nginxinc/nginx-prometheus-exporter

# References to other packs (optional)
# References are grouped by the type: operating-system, database, webserver, queue, ..
# The reference under the type is a at least one system, so at least one operating-system, database, ..
authors:
    - Deanna Schaeffer
    - James Womack
    - Rishin Pandit
    - Caitlin Littlejohn
    - Christina Perez
